### ISSUE TITLE
paste on login

### ISSUE THREAD

**Issue by lyndell** [gittyapp/feedback#24]
Can't paste my password into the password field.  I copy the password from AgilleBit's 1Password and attempt past into GittyApp.  No Paste popup.  Reproduced on the iPhone and iPad.  Not an apparent quirk with iOS.  Closed and reopened the GittyApp.

**Comment by mps** [comment]
@lyndell @trentmilton @zmoog sorry for the delay here but this will be fixed in 2.1.2

Thanks
